name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
api-version: 1.13
authors: [Gimme]
description: ${project.description}

commands:
  hc:
    description: Immediately respawn.
  hc respawn:
    description: Immediately respawns the specified player.